#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/a3eeeaca-3b0f-4662-9843-e99dfdb897a3/services/data/{version}/chatter # baseUri: https://mocksvc.mulesoft.com/mocks/df8386bf-085c-46bd-aaef-435cf8b7fd90/services/data/{v1}/chatter 
 
title: accountDetails
version: v1

protocols: [HTTP]
mediaType: application/json  

uses: 
  library: library.raml

securitySchemes: 
  oauth_2.0 : !include securityScheme.raml

securedBy: oauth_2.0

/accountdetails:
 get:
   description:  get all acount details
   responses: 
     200:
       body: 
        application/json:
         type: library.Accounts
         example: !include AccountDetailsExample.raml

     400:
       body: 
         application/json:
           type: library.Error
           example: {"message":"Invalid Request please check url",                         "code":400}   
     500:
       body:
        application/json:
          type: library.Error
          example: {"message":"server not found", "code":500}   

         
           