#%RAML 1.0 NamedExample
value:
  [{
      "PrincipalAmount" : "200000",
      "InterestAmount" : "1000",
      "InsuranceAmount" : "10000",
      "EscrowAmount" : "5000",
      "PmiAmount" : "200",
      "FeesAmount" : "220",
      "BalanceAsOf" : "2018-08-15",
      "PrincipalBalance" : "200000"
    },
    {
      "PrincipalAmount" : "200000",
      "InterestAmount" : "1000",
      "InsuranceAmount" : "10000",
      "EscrowAmount" : "5000",
      "PmiAmount" : "200",
      "FeesAmount" : "220",
      "BalanceAsOf" : "2018-08-15",
      "PrincipalBalance" : "200000"
    }
  ]