#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/89203cf6-ebd2-4e60-bbfb-ee4b637506fc/api/v1/dda/ # baseUri: /api/v1/dda/
title: paymentdetails
description: Getting payment details for perticular loan account
version: v1
protocols: [HTTPS]
mediaType: application/json

uses: 
  library: paymentlibrary.raml

securitySchemes: 
  oauth2_0: !include oauth_2.0.raml

securedBy: oauth2_0   

/loans/payments/{accountId}:
 get:
  description: Payment details for loan account
  headers:
   Accept: 
    type: string
    default: 
     application/json
     
  responses: 
   200:
    body:
     application/json:
       example: 
             !include paymentdetailsexample.raml
          
         
          
   400:
    body: 
     application/json:
       type: library.error
       example:
        {
          code: "400",
          message: "Invalid request parameter passed"
        }

   401:
    body: 
     application/json:
        type: library.error
        example:
         {
          code: "401",
          message: "You are not authorized"
         }  
   
   404:
    body: 
     application/json:
       type: library.error
       example:
        {
          code: "404",
          message: "Account not found"
        }
   
   405:
    body: 
     application/json:
       type: library.error
       example:
        {
          code: "405",
          message: "Method not allowed"
        }

   500:
    body: 
     application/json:
       type: library.error
       example:
        {
          code: "500",
          message: "Opps! Something went wrong"
        }                 