#%RAML 1.0 NamedExample
    {
          "accountId" : "1357902469",
          "originalPrincipal" : "300000",
          "loanTerm" : "5",
          "totalNumberOfPayments": "12",
          "paymentFrequency" : "MONTHLY",
          "paymentDetails": [
                              {
                                "principalAmount" : "200000",
                                "interestAmount" : "1000",
                                "insuranceAmount" : "10000",
                                "escrowAmount" : "5000",
                                "pmiAmount" : "200",
                                "feesAmount" : "220",
                                "balanceAsOf" : "2018-08-15",
                                "principalBalance" : "200000"
                              },
                              {
                                "principalAmount" : "200000",
                                "interestAmount" : "1000",
                                "insuranceAmount" : "10000",
                                "escrowAmount" : "5000",
                                "pmiAmount" : "200",
                                "feesAmount" : "220",
                                "balanceAsOf" : "2018-08-15",
                                "principalBalance" : "200000"
                              }
  ]
 }