#%RAML 1.0 NamedExample
value: {
            "loanId":1123,
            "accountId":125,
            "loanDescription":"Loan on Property",
            "initialLoanBalance":50000,
            "loanStartDate":"01/01/2016",
            "currentLoanBalance":50000,
            "dateAsOf":"20/09/208",
            "loanRate":3,
            "loanPaymentAmount":120000,
            "loanPaymentFrequency":"MONTHLY",
            "loanPaymentInitial":21,
            "loanPaymentsRemaining":3,
            "loanMaturityDate":"20/09/2019",
            "loanInterestToDate":7000,
            "loanTotalProjectedInterest":10000,
            "loanNextPaymentDate":"20/10/2018"
        }
