#%RAML 1.0 NamedExample
value:
  [{
    "AccountId": "1001001009768",
    "AccountType": "INSTALLMENT",
    "AccountNumber": "234576542345",
    "Nickname": "John",
    "Currency": "INR",
    "InterestRate": 9.50,
    "DisplayName": "Deposit Account",
    "BalanceAsOf": "2018-09-13",
    "CurrentBalance": 1200.00,
    "MaturityDate": "2018-12-12",
    "Status": "OPEN"
  },
  {
    "AccountId": "12341001009768",
    "AccountType": "SAVINGS",
    "AccountNumber": "1043416542345",
    "Nickname": "Doe",
    "Currency": "INR",
    "InterestRate": 10.50,
    "DisplayName": "Deposit Account",
    "BalanceAsOf": "2018-10-13",
    "CurrentBalance": 3400.00,
    "MaturityDate": "2018-11-12",
    "Status": "OPEN"
  }]