#%RAML 1.0 NamedExample
value:
  [{
    "accountId": "1001001009768",
    "accountType": "INSTALLMENT",
    "accountNumber": "234576542345",
    "nickname": "John",
    "interestRate": 9.50,
    "balanceAsOf": "2018-09-13",
    "currentBalance": 1200.00,
    "maturityDate": "2018-12-12",
    "status": "OPEN"
  },
  {
    "accountId": "12341001009768",
    "accountType": "SAVINGS",
    "accountNumber": "1043416542345",
    "nickname": "Doe",
    "interestRate": 10.50,
    "balanceAsOf": "2018-10-13",
    "currentBalance": 3400.00,
    "maturityDate": "2018-11-12",
    "status": "OPEN"
  }]