#%RAML 1.0 Library
usage: library

types: 
  identifier:
   type: string
   pattern: \d+
    maxLength:128
  memo:
   type: string
   maxLength: 255
  transferStatusStatus:
   type: string

  Transfer:
      type: object
      properties: 
       transferID: identifier
       fromAccountId: identifier
       toAccountId: identifier
       amount: number
       memo: string 
  TransferStatus:
      type: Transfer
      properties: 
       transferId: identifier
       referenceId: identifier
       transferStatusStatus:
             enum: [SUCCESS, NOFUNDS, PENDING, FAILURE]

  Error:
   type: object
   properties: 
     code: string
     message: string