#%RAML 1.0 NamedExample

{
           status: Failure
           "transferID":"111222333444558",
           "fromAccountId": "146464",
           "toAccountId": "365768",
           "amount": "5000",
           "memo": "billpayment",
  }