#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: authentication for transfer status
describedBy: 
  headers: 
    Authorization:
      description: used to send a valid OAuth 2 access token. Do not use with the"access_token" query string parameter.
      type: string
    queryparameters:
    access_token:
      type: string
  responses:
   
    400:
      description: Bad OAuth Request

    401:
      description: Bad or Expired token
      
settings: 
  authorizationUri: https://api/v1/transfer/oauth2/authorize  
  accessTokenUri: https://api/v1/transfer/oauth2/token
  authorizationGrants: implicit   
      
         
        

    
    
    
        
    


