#%RAML 1.0 
baseUri: https://mocksvc.mulesoft.com/mocks/fff3cdc2-ffc0-4f87-94d7-2ceea7f05258 # 
title: Give transfer details on the basis of Transfer Status        
version: v1
protocols: [HTTPS]
mediaType: application/json
uses:
 library: entity.raml

securitySchemes:
 TransferSecurityScheme: !include securitySchemeTest.raml
securedBy: TransferSecurityScheme

/api/v1/transfer: 

 get:
  queryParameters: 
     status : string
  responses: 
   200:
    body: 
     application/json:
       example: !include exampleData.raml
   400:
     body:
      application/json:
          example:
           {
             code: "400",
            "message": "Bad Request-the request hostname is                     invalid"
          }

      
   404:
       body: 
         application/json:
           example:
            {
               code: "404",
               "message":"resource Not Found" 
            }  

   500:
        body: 
         application/json:
           example:
            {
               code: "500",
               "message":"Internal server error" 
            } 


   408:
        body: 
         application/json:
           example:
            {
               code: "408",
               "message":"Reqest TimeOut" 
            } 