#%RAML 1.0 NamedExample
value:
 "DepositAccount":
  {
   "AccountId" : "0004452101",
   "AccountType": "CHECKING", 
   "DisplayName": "ABC Deposit Account" ,
   "Status": "OPEN",
   "Description": "Deposit Account" ,
   "ParentAccountId": "0001001" ,
   "Nickname": "My Deposit Account01",
   "Currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60.5
    },
    "AccountNumber": "0004452102" ,
    "InterestRate": 3.5,
    "InterestRateType": "FIXED" ,
    "MicrNumber": "MICR0001001DEPO",
    "BalanceAsOf": 2018-12-31T23:59:00,
    "CurrentBalance": 100000.00 ,
    "OpeningDayBalance": 50000.00,
    "AvailableBalance": 100000.00 ,
    "AnnualPercentageYield": 5.00,
    "InterestYtd": 4.50,
    "MaturityDate": 2028-12-31T21:59:59,
    "Term": 10.00
  }