#%RAML 1.0 NamedExample
value:
 "InvestmentAccount":
  {
   "AccountId" : "0004452102",
   "AccountType": "401K", 
   "DisplayName": "ABC Investment Account" ,
   "Status": "OPEN",
   "Description": "Investment Account" ,
   "ParentAccountId": "0001001" ,
   "Nickname": "My Investment Account01",
   "Currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60.5
    },
    "AccountNumber": "0001001123" ,
    "InterestRate": 3.5,
    "InterestRateType": "FIXED" ,
    "MicrNumber": "MICR0001001DEPO",
    "BalanceAsOf": 2018-12-31T23:59:00,
    "CurrentValue": 100000.00 ,
    "AllowedCheckWriting": true ,
    "AllowedOptionTrade":  true,
    "AvailableCashBalance": 90000.00,
    "Margin": false,
  }