#%RAML 1.0 NamedExample
value:
 "LOCAccount":
  {
   "AccountId" : "0004452103",
   "AccountType": "COMMERCIALLINEOFCREDIT", 
   "DisplayName": "ABC Loc Account" ,
   "Status": "OPEN",
   "Description": "Loc Account" ,
   "ParentAccountId": "0001001" ,
   "Nickname": "My Loc Account01",
   "Currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60.5
    },
    "AccountNumber": "0001001123" ,
    "InterestRate": 3.5,
    "InterestRateType": "FIXED" ,
    "MicrNumber": "MICR0001001DEPO",
    "CreditLine": 60000 ,
    "AvailableCredit": 40000,
    "NextPaymentAmount": 4500 ,
    "NextPaymentDate": 2018-12-31T23:59:00 ,
    "PrincipalBalance": 200000 ,
    "CurrentBalance": 80000,
    "AvailableCash": 50000 ,
  } 