#%RAML 1.0
title: api to retrieve addresses for a customer services
version: v1
protocols: [HTTP]
mediaType: apllication/json
uses: 
  library : entity.raml
    
/v1/customer/addresses/{customerId}:
    post:
     description:  Request a customerId from the address of available                    customer call
     body: 
      application/json:
         example:
          {
            
          "cutomerId": "123434"
          }

     responses:
      200:
       body:
        applicaton/json:
          example:
           !include example.raml
      400:
       body:
        applicaton/json:
         example:
          {
            "code": "400",
            "message": "Customer Request not found"
          }


      404:
       body:
        applicaton/json:
         example:
          {
            "code": "404",
            "message": "Customer not found"
          }
      
      500:
       body: 
        application/json:
         example:
          {
            "code": "500",
            "message": "Internal Server Error"
          }
         