#%RAML 1.0 NamedExample

{
      "cutomerId": "123434",
      "name": [
        {
          "first":"Michael",
          "middle":"J",
          "last":"Smith",
          "company":"Acme"
        }
      ],

        "DateOfBirth": "1990-01-10",
        "Address": [
          {
                  "DeliveryAddressType": "home",
                  "line 1":"963 Lovelace Road ",
                  "line 2":" Tampa Bay",
                  "city":" California ",
                  "state":" US ",
                  "zip ":" 90001",
                  "country":" United states "
          },
          {
                    "type":" business",
                    "line 1":"964 Lovelace Road",
                    "line 2":" Tampa 1 Bay",
                    "city":" California ",
                    "state":" US ",
                    "zip ":" 90001",
                    "country":" United states "
          },
          {
                      "type":"mailing ",
                      "line 1":"965 Lovelace Road",
                      "line 2":" Tampa2 Bay",
                      "city":" California ",
                      "state":" US ",
                      "zip ":" 90001",
                      "country":" United states "
          }
        ],
  }