#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/889a8359-1e6a-4fb0-bcc6-b18bf2cfc081 # 
title: Status of Transfer between Accounts
types:
 Identifier: 
    type: string
    pattern: \d+ 
    maxLength: 128
 AccountDescriptor:
    type: object
    properties: 
      accountId: Identifier
      accountType:

        enum: [401A,401K,403B,AUTOLOAN,CD,CHARGE,CHECKING,COMMERCIALLINEOFCREDIT,                COMMERCIALLOAN,COVERDELL,CREDITCARD,ESCROW,ESOP,GUARDIAN,                         HOMEEQUITYLOAN,HOMELINEOFCREDIT,INSITUTIONALTRUST,INSTALLMENT,IRA,                KEOG,LINEOFCREDIT,LOAN,MILATARYLOAN,MONEYMARKET,MORTGAGE,                         PERSONALLOAN,ROLLOVER,ROTH,SARSEP,SAVINGS,SMBLOAN,STUDENTLOAN,                    TAXABLE,TDA,TRUST]

      displayName: string
      description: string
      accountStatus:
      
        enum: [OPEN, CLOSED, PENDINGOPEN, PENDINGCLOSE, DELINQUENT,
              PAID, NEGATIVECURRENTBALANCE,APPROVED,REJECTED]
      
 Account:
    type: AccountDescriptor
    properties: 
      parentAccountId: Identifier
      nickname: string
      accountNumber: string
      interestRate: number

 Transfer:
    type: AccountDescriptor
    properties: 
      parentAccountId: Identifier
      nickname: string
      accountNumber: string
      interestRate: number

 TransferStatus:
    type: AccountDescriptor
    properties: 
      TransferId: number
      ReferenceId: Identifier
      status:
       enum: [FAILURE,NOFUNDS,PENDING,SUCCESS]     
      TransferDate : number
        
 Transaction:
    type: object
    properties: 
      accountId: Identifier
      transactionId: Identifier
      transactionTimestamp: date-only
      description: string
      imageIds: string[]
      status: 
        enum: [PENDING, MEMO, POSTED, AUTHORIZATION]
      amount: number
     
/api/v1/transfer/status:
 post:
   body: 
     application/json:
       example:
        {
         "transferId":="111222333444555"
        }
   responses: 
     200:
       body: 
         application/json:
          example: !include design.raml
                           
     404:
      body: 
        application/json:
          example:
           {
             message: "Transfer  not Found"
           }
     401:
      body: 
        application/json:
          example:
           {
             message: "Customer not authorized"
           }    
     400:
      body: 
        application/json:
          example:
           {
             message: "insufficient funds"
           }  
     500:
      body: 
        application/json:
          example:
            {
              message: "Transfer not available due to end of day processing"
            }
          
      
