#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/ecd1489c-2927-42ee-b94f-d454bd3daad9 # 
title: AccountInformation
description: Rest API for getting account information
version: v1
protocols: [HTTP]
mediaType: application/json

uses : 
  libarary: Accountlibrary.raml

/v1/accounts: 
 get:
  description: The query parameter is specified
  queryParameters: 
    transferIn: boolean
    transferOut: boolean
    page: integer
  responses: 
    200:
     body:
      application/json:
       type: libarary.Accounts
       example: !include accountexample.raml
    404:
     body: 
       application/json:
         example:
          {
             code : 404,
             message : "Account not found"

          } 
    
    400:
     body:
      application/json:
        example: 
         {
            code : 400,
            message : "Bad Request!! please enter valid query                               parameter"
         }
