#%RAML 1.0 NamedExample
value:
 {
   "total" : 1,
   "totalPages" : 1,
   "page" : 1,
   "account" : 
  [  
   {
           "accountId"        : "1357902468",
           "accountType"      : "SAVINGS",
           "displayName"      : "Saving Account",
           "nickName"         : "My Savings Account",
           "lineOfBusiness"   : "consumer",
           "accountNumber"    : "4561237890",
           "interestRate"     :  3,
           "currency"         : "INR",
           "transferIn"       :  false,
           "transferOut"      :  false,
           "interestRateType" : "FIXED"
 },
 {
           "accountId"        : "1357902468",
           "accountType"      : "SAVINGS",
           "displayName"      : "Saving Account",
           "nickName"         : "My Savings Account",
           "lineOfBusiness"   : "consumer",
           "accountNumber"    : "4561237890",
           "interestRate"     :  3,
           "currency"         : "INR",
           "transferIn"       :  false,
           "transferOut"      :  false,
           "interestRateType" : "FIXED"
 }
 ]}