#%RAML 1.0 NamedExample
value:
 {
        "accountId" : "1357902468",
        "statementId" : "875376081768363584639",
        "statementDate" : 2018-04-04,
        "description" : "Statement for 2018-04-04"
 }