#%RAML 1.0 NamedExample
value:
        {
          "Total": 3, 
          "TotalPages": 4,
          "Page": 1,
          "AccountArray": 
            [
                {
                    "BalanceAsOf": 2018-09-10,
                    "CurrentBalance": 23.00,
                    "ParentAccountId": "45768",
                    "Status": "OPEN",
                    "AvailableBalance": 45,
                    "AccountId": "135790246",
                    "AccountType": "AUTOLOAN",
                    "DisplayName" : "Savings Account",
                    "Nickname": "My Savings Account ",
                    "AccountNumber": "4561237890",
                    "InterestRate": 3,
                    "Currency": "INR",
                    "Transactions": 
                    [
                      {
                        "transactionType": "CHECK",
                        "payee":  "megha",
                        "checkNumber": "1234567",
                      },
                      {
                        "transactionType": "CHECK",
                        "payee":  "megha",
                        "checkNumber": "234567",
                      }
                    ]
                },
                {
                    "BalanceAsOf": 2018-09-10,
                    "CurrentBalance": 23,
                    "AvailableBalance": 45,
                    "ParentAccountId": "45768",
                    "Status": "OPEN",
                    "AccountId": "135790246",
                    "AccountType": "AUTOLOAN",
                    "DisplayName" : "Savings Account",
                    "Nickname": "My Savings Account ",
                    "AccountNumber": "4561237890",
                    "InterestRate": 3,
                    "Currency": "INR",
                    "Transactions": 
                    [
                      {
                        "transactionType": "CHECK",
                       "payee":  "megha",
                        "checkNumber": "1234567",
                      },
                      {
                        "transactionType": "CHECK",
                       "payee":  "megha",
                        "checkNumber": "234567",
                      }
                    ]
                  },
        {
                "BalanceAsOf": 2018-09-10,
                "PrincipalBalance": 23,
                "ParentAccountId": "45768",
                "Status": "OPEN",
                "OriginalPrincipal": 45,
                "TotalNumberOfPayments": 10,
                "PaymentFrequency": "MONTHLY",
                "AccountId": "135790246",
                "AccountType": "AUTOLOAN",
                "DisplayName" : "Savings Account",
                "Nickname": "My Savings Account ",
                "AccountNumber": "4561237890",
                "InterestRate": 3,
                "Currency": "INR",
                "Transactions": 
                [
                  {
                    "transactionType": "CHECK",
                  },
                  {
                    "transactionType": "CHECK",
                  }
                ]
            },
            {
                "BalanceAsOf": 2018-09-10,
                "PrincipalBalance": 23,
                "ParentAccountId": "45768",
                "Status": "OPEN",
                "OriginalPrincipal": 45,
                "LoanTerm": 12,
                "TotalNumberOfPayments": 10,
                "PaymentFrequency": "MONTHLY",
                "AccountId": "135790246",
                "AccountType": "AUTOLOAN",
                "DisplayName" : "Savings Account",
                "Nickname": "My Savings Account ",
                "AccountNumber": "4561237890",
                "InterestRate": 3,
                "Currency": "INR",
                "Transactions": 
                [
                  {
                    "transactionType": "CHECK",
                  },
                  {
                    "transactionType": "CHECK",
                  }
                ]
            }]
        }