#%RAML 1.0 NamedExample
value: 
  {
   "accountId" : "0004452102",
   "accountType": "CHECKING", 
   "displayName": "ABC Deposit Account" ,
   "status": "OPEN",
   "description": "Deposit Account" ,
   "parentAccountId": "0001001" ,
   "nickname": "My Deposit Account01",
   "currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60
    },
    "accountNumber": "0004452102" ,
    "interestRate": 3,
    "interestRateType": "FIXED" ,
    "micrNumber": "MICR0001001DEPO",
    "balanceAsOf": 2018-12-31,
    "currentBalance": 100000 ,
    "openingDayBalance": 50000,
    "availableBalance": 100000 ,
    "annualPercentageYield": 5,
    "interestYtd": 4,
    "maturityDate": 2028-12-31,
    "term": 10
  }