#%RAML 1.0 NamedExample
value:
  {
   "accountId" : "0004452102",
   "accountType": "401K", 
   "displayName": "ABC Investment Account" ,
   "status": "OPEN",
   "description": "Investment Account" ,
   "parentAccountId": "0001001" ,
   "nickname": "My Investment Account01",
   "currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60
    },
    "accountNumber": "0001001123" ,
    "interestRate": 3,
    "interestRateType": "FIXED" ,
    "micrNumber": "MICR0001001DEPO",
    "balanceAsOf": 2018-12-31,
    "currentValue": 100000 ,
    "allowedCheckWriting": true ,
    "allowedOptionTrade":  true,
    "availableCashBalance": 90000,
    "margin": false,
  }