#%RAML 1.0 NamedExample
value:
  {
   "accountId" : "0004452104",
   "accountType": "LOAN", 
   "displayName": "ABC Loan Account" ,
   "status": "OPEN",
   "description": "Loan Account" ,
   "parentAccountId": "0001001" ,
   "nickname": "My Loan Account01",
   "currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60
    },
    "accountNumber": "0001001123" ,
    "interestRate": 3,
    "interestRateType": "FIXED" ,
    "micrNumber": "MICR0001001DEPO",
    "balanceAsOf": 2018-12-31,
    "principalBalance": 100000,
    "escrowBalance": 90000 ,
    "originalPrincipal":  100000,
    "originatingDate": 2017-12-31,
    "loanTerm": 30,
    "totalNumberOfPayments": 19,
    "nextPaymentAmount": 15000,
    "nextPaymentDate": 2019-01-31,
    "paymentFrequency": "MONTHLY",
    "compoundingPeriod": "SEMIANNUALLY",
    "maturityDate": 2025-12-31 
  }