#%RAML 1.0 NamedExample
value:
  {
   "accountId" : "0004452103",
   "accountType": "COMMERCIALLINEOFCREDIT", 
   "displayName": "ABC Loc Account" ,
   "status": "OPEN",
   "description": "Loc Account" ,
   "parentAccountId": "0001001" ,
   "nickname": "My Loc Account01",
   "currency": 
    {
      "currencyCode": "INR", 
      "currencyRate": 60
    },
    "accountNumber": "0001001123",
    "interestRate": 3,
    "interestRateType": "FIXED" ,
    "micrNumber": "MICR0001001DEPO",
    "balanceAsOf": 2018-12-31,
    "creditLine": 60000 ,
    "availableCredit": 40000,
    "nextPaymentAmount": 4500,
    "nextPaymentDate": 2018-12-31,
    "principalBalance": 200000,
    "currentBalance": 80000,
    "availableCash": 50000,
  } 