#%RAML 1.0
title: entity
description: entities description 

types: 
 identifier:
  type: string
  pattern: \d+
  maxLength: 128
 AccountDescriptor:
  type: object
  properties: 
    accountID: identifier
    accountType:
     enum: [INVESTMENT_ACCOUNT, LOAN_ACCOUNT,DEPOSIT_ACCOUNT,COMMERCIALLOAN]
    displayname: string
    description: string
    accountStatus:
     enum: [OPEN, CLOSED, PENDINGOPEN, PENDINGCLOSE, DELINQUENT,
              PAID, NEGATIVECURRENTBALANCE,APPROVED,REJECTED]

 Account:
  type: AccountDescriptor
  properties: 
    parentAccountId: identifier
    nickname: string
    accountNumber: string
    interestRate: number
    curreny: currency[]

 currency:
  type: object  # not sure extends account
  properties: 
    currencyCode: string
    currencyRate: string
    originalCurrencyCode: string

 InvestmentAccount:
  type: Account
  properties: 
    balanceasOf: datetime
    allowedCheckWriting: boolean
    allowedOptionTrade: boolean
    currentValue: boolean
    availableCashBalance: number
    margin: boolean
    marginBalance: boolean
    shortBalance: number
    brokerId: string
    planId: string
    rolloverAmount: number
    employerName: string
    balanceList: InvestmentBalance[]

 InvestmentBalance:
  type: object
  properties: 
   balanceName: string
   balanceDescription: string
   balanceType:
    enum: [AMOUNT, PERCENTAGE]
   balanceValue: number
   balanceDate: datetime
   currency: currency[]