#%RAML 1.0 Library
#title: entity
#description: entities description 

types: 
 identifier:
  type: string
  pattern: \d+
  maxLength: 128
  
 accountType:
   type: string
   enum: [SAVINGS,LOAN,PERSONALLOAN,COMMERCIALLOAN]

 accountStatus:
  type: string
  enum: [OPEN, CLOSED, PENDINGOPEN, PENDINGCLOSE, DELINQUENT,
              PAID, NEGATIVECURRENTBALANCE,APPROVED,REJECTED]

# Account description tables detail
 AccountDescriptor:
  type: object
  description: account descriptor entity 
  properties: 
    accountId: identifier
    status: accountStatus
    displayName: string
    description: string
    accountType: accountType   
    
# Account tables details 
 Account:
  type: AccountDescriptor
  description: InvestmentAccount 
  properties: 
    #parentAccountId: identifier
    nickname: string
    accountNumber: string
    interestRate: number

# Currey tables details 
 currency:
  type: object
  description: currency details entity
 properties:
 currencyCode: 
      enum: [AED,AUD,USD,BMD,BND,CAD,CHF,EUR]
 currencyRate: number
 originalCurrencyCode: 
     enum: [AED,AUD,USD,BMD,BND,CAD,CHF,EUR]
   
# investment account tables details
 InvestmentAccount:
  type: Account
  description: investment account details
  properties: 
   allowedCheckWriting: boolean
   allowedOptionTrade: boolean
   currentValue: number
   availableCashBalance: number
   margin: boolean
   marginBalance: boolean
   shortBalance: number
   brokerId: string
   planId: string
   rolloverAmount: number
   employerName: string
   balanceList: InvestmentBalance[]
   currency: currency

# investmen balance table details 
 InvestmentBalance:
  type: object
  description: investmen account blance 
  properties: 
   balanceName: string
   balanceDescription: string
   balanceType:
    enum: [AMOUNT, PERCENTAGE]
   balanceValue: number
   balanceDate: date-only
   currency: currency
   
 Errors:
  type: object
  description: http errors codes 
  properties: 
    code: 
    type: string
    message: 
     type: string
