#%RAML 1.0
title: TransferStatus
version: v1
protocols: [HTTPS]
baseUri: https://mocksvc.mulesoft.com/mocks/f21b6d9f-5e25-4e0c-8fca-ecf85f3bde55/{version}/stockSweepSecurity # baseUri: https://mocksvc.mulesoft.com/mocks/2f352b31-373e-4e6c-a338-aaa1dbd42c22/{version}/stockSweepSecurity # baseUri: https://mocksvc.mulesoft.com/mocks/767db4e7-7df6-47a9-8831-c75c7d29c0ce/{version}/stockSweepSecurity # baseUri: https://StargateTraining/{version}/transferStatus
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.
  
types:
  TransferStatus:
    properties: 
      TransferId:
        type: integer
        minimum: 1
        
      ReferenceId:
        type: integer
        minimum: 1
      Status: TransferStatusStatus
      TransferDate: datetime  
  TransferStatusStatus:
    description: this is the status of all transfer
    displayName: TransferStatusStatus      
    type: string
    enum:
      - SUCCESS
      - NOFUNDS
      - PENDING
      - FAILURE
  Transfer:
    properties: 
      TransferId: integer
      FromAccountId: string
      ToAccountId: string
      Amount: integer
      Memo: string
      PaymentDetails: string

/transfer:
  get:
    description: Get Stock Security details for the provided holding
    queryParameters: 
      traferstatus:
        description: "hngh"
        required: true
        type: string
        enum: ["SUCCESS","PENDING","FAILURE","NOFUNDS"] 
    responses:
      200:
        body:
          application/json:
            type: Transfer[]
            example: [{"TransferId":1, "FromAccountId":"123", "ToAccountId": "123", "Amount":1000, "Memo": "family", "PaymentDetails": "xyz"}, {"TransferId":2, "FromAccountId":"1234", "ToAccountId": "12376", "Amount":1500, "Memo": "family", "PaymentDetails": "xyzgjy"}, {"TransferId":3, "FromAccountId":"1235", "ToAccountId": "112543", "Amount":15000, "Memo": "financial", "PaymentDetails": "xxxx"}]