#%RAML 1.0 
title: debtsecurity
version: v1
protocols: [HTTPS]
baseUri: https://security/api
mediaType: application/json
annotationTypes:
  Document:
types:
  DebtSecurity:
    (Document):
    properties:
      ParValue: integer
      DebtType: 
          enum: [COUPON, ZERO]
      DebtClass: string
      CouponRate: integer
      CouponDate: datetime
      CouponMatureFrequency: 
        enum: [MONTHLY,QUARTERLY, SEMIANNUAL, ANNUAL, or OTHER]
      CallPrice: integer
      YieldToCall: integer
      CallDate: datetime
      CallType: 
        enum: [CALL, PUT, PREFUND, MATURITY]
      YieldToMaturity: integer
  Holding:
    properties:
      (Id):
      HoldingId: string
      SecurityType: DebtSecurity       
/debtsecuritydetails:
  get:
   description: If the user has debtsecurity type then this method disp;ays debt security details using holdingId else tech-diff page is displayed
   queryParameters:
     HoldingId: string
   responses:
     200:
      body:
        application/json:
         type: DebtSecurity